name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  Solution_Name: GradesChecker/GradesChecker.sln
  Test_Project_Path: GradeCheck.nUnitTests/GradeCheck.nUnitTests.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Build
      run: dotnet build ${{ env.Solution_Name }}

    - name: Restore NuGet Packages
      run: |
        dotnet restore GradesChecker
        dotnet restore GradeCheck.nUnitTests

    - name: Run Code Formatter
      run: dotnet format ${{ env.Solution_Name }}

    - name: Ensure TestResults Directory Exists
      run: mkdir -p TestResults
      working-directory: GradesChecker
  
    - name: Test with Coverage
      run: |
        dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
      working-directory: GradesChecker

    - name: Publish Test Results
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Results
        path: '**/TestResults/*.trx'

    - name: Notify Failure
      if: failure()
      run: echo "Workflow failed! Please check the logs."
