name: Run tests and publish results on PRs

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
      Solution_Name: GradesChecker.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: GradeCheck.nUnitTests.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
     

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: GradesChecker.sln

      - name: Run tests
        run: |
          mkdir -p test-results
          dotnet test --logger "trx;LogFileName=test-results.trx" --results-directory ./test-results
        continue-on-error: true

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-results/test-results.trx
